name: flutter_audio_manager_plus
description: The flutter_audio_manager_plus listens to, gets and modifies audio input/output devices.
version: 0.0.1
homepage: https://github.com/IhabZaidi/flutter_audio_manager_plus

environment:
    sdk: ">=2.12.0 <3.0.0"
    flutter: ">=2.5.0"

dependencies:
    flutter:
        sdk: flutter

dev_dependencies:
    flutter_test:
        sdk: flutter
flutter:
    plugin:
        platforms:
            android:
                package: com.yung.flutter_audio_manager
                pluginClass: FlutterAudioManagerPlugin
            ios:
                pluginClass: FlutterAudioManagerPlugin
